<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_OneStepCheckout
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var \Magento\Multishipping\Block\Checkout\Overview $block */
?>
<?php
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
/** @var \Magento\Checkout\Helper\Data $checkoutHelper */
$checkoutHelper = $block->getData('checkoutHelper');
?>
<?php $errors = $block->getCheckoutData()->getAddressErrors(); ?>
<?php foreach ($errors as $addressId => $error): ?>
    <div class="message message-error error">
        <?= $block->escapeHtml($error); ?>
        <?= $block->escapeHtml(__('Please see')); ?>
        <a href="#<?= $block->escapeHtml($block->getCheckoutData()->getAddressAnchorName($addressId)); ?>">
            <?= $block->escapeHtml(__('details below')); ?></a>.
    </div>
<?php endforeach;?>
<form action="<?= $block->escapeUrl($block->getPostActionUrl()); ?>"
      method="post"
      id="review-order-form"
      data-mage-init='{"orderOverview": {}, "validation":{}}'
      class="form multicheckout order-review">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <div class="block block-shipping">

        <div class="wk_osc_title"><?= $block->escapeHtml(__('Overview')); ?></div>

        <?php $mergedCells = ($taxHelper->displayCartBothPrices() ? 2 : 1); ?>

        <!-- start title -->
        <div id="wk_all_titles">
            <?php foreach ($block->getShippingAddresses() as $index => $address): ?>
                <span data-textId="#titleText<?= $block->escapeHtml($index + 1); ?>"
                class = "wk_titles_overview" id="wk_shipping_title<?= $block->escapeHtml($index + 1); ?>"
                data-id="#wk_shipping_add<?= $block->escapeHtml($index + 1); ?>">
                <a name="<?= $block->escapeHtml($block->getCheckoutData()
                        ->getAddressAnchorName($address->getId())); ?>"></a>
                    <div class="step-title wk_each_title" id="titleText<?= $block->escapeHtml($index + 1); ?>">
                        <strong><?= $block->escapeHtml(__('Address')); ?> <?= $block->escapeHtml($index + 1); ?>
                            <span>
                                <?= $block->escapeHtml(__('of')); ?>
                                <?= $block->escapeHtml($block->getShippingAddressCount())?>
                            </span>
                        </strong>
                    </div>
                </span>
            <?php endforeach; ?>
        </div>
        <!-- after title -->
        <!-- <div class="wk-loading-mask">
    <div class="wk-loader"></div>
</div> -->

        <div class="wk_add_content">
        <!-- <div class="wk-loading-mask wk-display-none">
    <div class="wk-loader"></div>
</div> -->

        <?php foreach ($block->getShippingAddresses() as $index => $address): ?>
            <div class="wk_shipping_add_one" id="wk_shipping_add<?= $block->escapeHtml($index + 1); ?>" >

            <?php if ($error = $block->getCheckoutData()->getAddressError($address)): ?>
                <div class="error-description"><?= $block->escapeHtml($error); ?></div>
            <?php endif;?>
                <div class="wk_shipping_add_overview">
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Shipping To')); ?></span>
                    </strong>
                    <div class="box-content">
                        <address>
                            <?= /* @noEscape */ $address->format('html') ?>
                        </address>
                    </div>
                </div>
                <div class="wk_shipping_method_overview">
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Shipping Method')); ?></span>
                    </strong>
                    <?php if ($_rate = $block->getShippingAddressRate($address)): ?>
                        <div class="box-content">
                            <?= $block->escapeHtml($_rate->getCarrierTitle()) ?>
                            (<?= $block->escapeHtml($_rate->getMethodTitle()) ?>)
                            <?php
                            $exclTax = $block->getShippingPriceExclTax($address);
                            $inclTax = $block->getShippingPriceInclTax($address);
                            $displayBothPrices = $taxHelper
                                ->displayShippingBothPrices() && $inclTax !== $exclTax;
                            ?>
                            <?php if ($displayBothPrices): ?>
                                <span class="price-including-tax"
                                    data-label="<?= $block->escapeHtml(__('Incl. Tax')); ?>">
                                    <?= /* @noEscape */ $inclTax ?>
                                </span>
                                <span class="price-excluding-tax"
                                    data-label="<?= $block->escapeHtml(__('Excl. Tax')); ?>">
                                    <?= /* @noEscape */ $exclTax; ?>
                                </span>
                            <?php else: ?>
                                <?= /* @noEscape */ $inclTax ?>
                            <?php  endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="wk_box_items_overview">
                    <div class="box-content">
                        <div class="order-review-wrapper table-wrapper">
                            <table class="items data table table-order-review"
                                id="overview-table-<?= $block->escapeHtml($address->getId()); ?>">
                                <caption class="table-caption"><?= $block->escapeHtml(__('Order Review')); ?></caption>
                                <thead>
                                <tr>
                                    <th class="col item" scope="col"><?= $block->escapeHtml(__('Item')); ?>
                                    </th>
                                    <th class="col price" scope="col"><?= $block->escapeHtml(__('Price')); ?></th>
                                    <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')); ?></th>
                                    <th class="col subtotal" scope="col"><?= $block->escapeHtml(__('Subtotal')); ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($block->getShippingAddressItems($address) as $item): ?>
                                    <?= /* @noEscape */ $block->getRowItemHtml($item) ?>
                                <?php endforeach; ?>
                                </tbody>
                                <tfoot>
                                    <?= /* @noEscape */ $block->renderTotals(
                                        $block->getShippingAddressTotals($address)
                                    ); ?>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        </div>

        <!-- addresses list ends -->

    </div>

    <?php if ($block->getQuote()->hasVirtualItems()): ?>
    <div class="block block-other">
        <?php $billingAddress = $block->getQuote()->getBillingAddress(); ?>
        <a name="<?= $block->escapeHtml($block->getCheckoutData()
            ->getAddressAnchorName($billingAddress->getId())); ?>"></a>
        <div class="block-title"><strong><?= $block->escapeHtml(__('Other items in your order')); ?></strong></div>
        <?php if ($error = $block->getCheckoutData()->getAddressError($billingAddress)):?>
                <div class="error-description"><?= $block->escapeHtml($error); ?></div>
        <?php endif;?>
        <div class="block-content">
            <strong class="subtitle">
                <span><?= $block->escapeHtml(__('Items')); ?></span>
                <a href="<?= $block->escapeUrl($block->getVirtualProductEditUrl()); ?>"
                   class="action edit"><span><?= $block->escapeHtml(__('Edit Items')); ?></span></a>
            </strong>
            <?php $mergedCells = ($taxHelper->displayCartBothPrices() ? 2 : 1); ?>
            <div class="order-review-wrapper table-wrapper">
                <table class="items data table table-order-review" id="virtual-overview-table">
                    <caption class="table-caption"><?= $block->escapeHtml(__('Items')); ?></caption>
                    <thead>
                        <tr>
                            <th class="col item" scope="col"><?= $block->escapeHtml(__('Product Name')); ?></th>
                            <th class="col price" scope="col"><?= $block->escapeHtml(__('Price')); ?></th>
                            <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')); ?></th>
                            <th class="col subtotal" scope="col"><?= $block->escapeHtml(__('Subtotal')); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($block->getVirtualItems() as $_item): ?>
                            <?= /* @noEscape */ $block->getRowItemHtml($_item) ?>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                    <?= /* @noEscape */ $block->renderTotals($block->getBillingAddressTotals()); ?>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?= /* @noEscape */ $block->getChildHtml('items_after') ?>

    <div id="checkout-review-submit" class="checkout-review">
        <div id="terms_condition"></div>
        <?= /* @noEscape */ $block->getChildHtml('agreements') ?>
        <div class="grand totals">
            <strong class="mark"><?= $block->escapeHtml(__('Grand Total:')); ?></strong>
            <strong class="amount">
                <?= /* @noEscape */ $checkoutHelper
                    ->formatPrice($block->getTotal()); ?>
            </strong>
        </div>
        <div class="actions-toolbar" id="review-buttons-container">
            <div class="primary">
                <button type="submit"
                        class="action primary submit"
                        id="review-button"><span><?= $block->escapeHtml(__('Place Order')); ?></span>
                </button>
            </div>
            <span id="review-please-wait"
                  class="please-wait load indicator"
                  style="display: none;"
                  data-text="<?= $block->escapeHtml(__('Submitting order information...')); ?>">
                <span><?= $block->escapeHtml(__('Submitting order information...')); ?></span>
            </span>
        </div>
    </div>
</form>
