<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_OneStepCheckout
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
/**
 * Ship to multiple address template
 *
 * @var $block \Magento\Multishipping\Block\Checkout\Addresses
 */
?>
<div style="float:left; width:600px;">
<!-- <div id="checkout-loader" style="display:none;">
        <div class="loader">
            <img src="<?php //= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?php //= $block->escapeHtmlAttr(__('Loading...')); ?>"
                 style="position: absolute;">
        </div>
    </div> -->
<form
      style="height: 400px;overflow:scroll;"
      id="checkout_multishipping_form"
      data-mage-init='{
          "multiShipping":{},
          "cartUpdate": {
               "validationURL": "<?= $block->escapeUrl($block->getUrl('multishipping/checkout/checkItems')) ?>",
               "eventName": "updateMulticartItemQty"
          }}'
      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      class="multicheckout address form">
    <div class="title">
        <strong><?= $block->escapeHtml(__('Please select a shipping address for applicable items.')) ?></strong>
    </div>
    <input type="hidden" name="continue" value="0" id="can_continue_flag"/>
    <input type="hidden" name="new_address" value="0" id="add_new_address_flag"/>
    <div class="table-wrapper">
        <table class="items data table" id="multiship-addresses-table">
            <caption class="table-caption">
                <?= $block->escapeHtml(__('Please select a shipping address for applicable items.')) ?>
            </caption>
            <thead>
            <tr>
                <th class="col product" scope="col"><?= $block->escapeHtml(__('Product')) ?></th>
                <th class="col qty" scope="col"><?= $block->escapeHtml(__('Qty')) ?></th>
                <th class="col address" scope="col"><?= $block->escapeHtml(__('Send To')) ?></th>
                <th class="col actions" scope="col">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getItems() as $_index => $_item): ?>
                <?php if ($_item->getQuoteItem()): ?>
                    <tr>
                        <td class="col product wk_add_product" data-th="<?= $block->escapeHtml(__('Product')) ?>">
                            <?= $block->getItemHtml($_item->getQuoteItem()) ?>
                        </td>
                        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                            <div class="field qty">
                                <label for="ship-<?= $block->escapeHtml($_index) ?>-<?=
                                $block->escapeHtml($_item->getQuoteItemId())
                                ?>-qty"
                                       class="label">
                                    <span><?= $block->escapeHtml(__('Qty')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="number"
                                           data-multiship-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                                           id="ship-<?= $block->escapeHtml($_index) ?>-<?=
                                            $block->escapeHtml($_item->getQuoteItemId()) ?>-qty"
                                           name="ship[<?= $block->escapeHtml($_index) ?>][<?=
                                            $block->escapeHtml($_item->getQuoteItemId()) ?>][qty]"
                                           value="<?= $block->escapeHtml($_item->getQty()) ?>"
                                           size="2"
                                           min="0"
                                           class="input-text qty"
                                           data-validate="{
                                               number: true, required:true, 'validate-greater-than-zero':true
                                               }"/>
                                </div>
                            </div>
                            <a
                               href="javascript:;"
                               data-inputVal = "#ship-<?= $block->escapeHtml($_index) ?>-<?=
                                $block->escapeHtml($_item->getQuoteItemId()) ?>-qty"
                               data-productId="<?= $block->escapeUrl($_item->getProductId()) ?> "
                               title="<?= $block->escapeHtml(__('Remove Item')) ?>"
                               class="action delete wk_remove_item"
                               data-multiship-item-remove="">
                                <span>
                                    <?= $block->escapeHtml(__('Remove item')) ?>
                                </span>
                            </a>
                        </td>
                        <td class="col address" data-th="<?= $block->escapeHtml(__('Send To')) ?>">
                            <?php if ($_item->getProduct()->getIsVirtual()): ?>
                                <div class="applicable">
                                    <?= $block->escapeHtml(__('A shipping selection is not applicable.')) ?>
                                </div>
                            <?php else: ?>
                                <div class="field address">
                                    <label for="ship_<?= $block->escapeHtml($_index) ?>_<?=
                                    $block->escapeHtml($_item->getQuoteItemId()) ?>_address"
                                           class="label">
                                        <span><?= $block->escapeHtml(__('Send To')) ?></span>
                                    </label>
                                    <div class="control" id="wk_address_list">
                                        <?= $block->getAddressesHtmlSelect($_item, $_index) ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button
                    id="button_submit_flag"
                    style="display: none;"
                    type="submit"
                    title="<?= $block->escapeHtml(__('Go to Shipping Information')) ?>"
                    class="action primary continue<?= $block->isContinueDisabled() ? ' disabled' : '' ?>"
                    data-role="can-continue"
                    data-flag="1"
                <?php if ($block->isContinueDisabled()): ?>
                    disabled="disabled"
                <?php endif; ?>>
                <span><?= $block->escapeHtml(__('Go to Shipping Information')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <button type="submit"
                    data-multiship-item-update=""
                    class="action update"
                    data-role="can-continue"
                    style="display: none;"
                    data-flag="0">
                <span><?= $block->escapeHtml(__('Update Qty &amp; Addresses')) ?></span>
            </button>
        </div>
    </div>
</form>

<div id="custom-component" data-bind="scope:'customcomponent'" style="margin-top: 15px;">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#custom-component": {
            "Magento_Ui/js/core/app": {
            "components": {
                    "customcomponent": {
                        "component": "Webkul_OneStepCheckout/js/view/shipping_test"
                    }
                }
            }
        }
    }
    </script>
    <button type="submit"
            data-multiship-item-update=""
            class="action update"
            data-role="can-continue"
            id="update_qty"
            data-flag="0">
        <span><?= $block->escapeHtml(__('Update Products Qty')) ?></span>
    </button>
</div>

</div>

<div id = "popup-modal" style="display:none">
    <?= /*@noEscape*/ $block->getBlockHtml('customer_address_edit');
    ?>
</div>
<script id="some-template" type="text/x-magento-template">
        <option value="<%- data.count %>">
                <%- data.content %>
        </option>
</script>

