<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_OneStepCheckout
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/**
 * Multishipping checkout billing information
 *
 * @var $block \Magento\Multishipping\Block\Checkout\Billing
 */
?>
<div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"billingLoader": {}}'>
    <div class="loader">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
             alt="<?= $block->escapeHtml(__('Loading...')); ?>"
             style="position: absolute;">
    </div>
</div>
<script>
    window.checkoutConfig = <?= /* @noEscape */ $block->getCheckoutData()->getSerializedCheckoutConfigs(); ?>;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.customerData = window.checkoutConfig.customerData;
</script>
<div id="checkout" data-bind="scope:'checkoutMessages'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "checkoutMessages": {
                            "component": "Magento_Ui/js/view/messages",
                            "displayArea": "messages"
                        }
                    }
                }
            }
        }
    </script>
</div>
<div id ="wk_osc_billing_div">
    <form
        action="<?= $block->escapeUrl($block->getPostActionUrl()); ?>"
        method="post"
        id="multishipping-billing-form"
        class="form multicheckout billing">



        <div class="block block-billing" style="display:none">
            <div class="block-content">
                <div class="box box-billing-address">
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Billing Address')); ?></span>
                        <a href="javascript:;" class="action" id="wk_choose_billing">
                            <span><?= $block->escapeHtml(__('Change')); ?></span>
                        </a>
                    </strong>
                    <div class="box-content">
                        <address>
                            <?= /* @noEscape */ $block->getCheckoutData()->getAddressHtml($block->getAddress()); ?>
                        </address>
                    </div>
                </div>
                <div class="box box-billing-method">
                    <fieldset class="fieldset">
                        <legend class="legend box-title">
                            <span><?= $block->escapeHtml(__('Payment Method')); ?></span>
                        </legend><br>
                        <div class="box-content">
                            <?= $block->getChildHtml('payment_methods_before') ?>
                            <?php /* Payment methods forms list */ ?>
                            <dl class="checkout-payment-method" id="payment-methods">
                                <?php
                                $methods = $block->getMethods();
                                $methodsCount = count($methods);
                                $methodsForms = $block->hasFormTemplates() ? $block->getFormTemplates(): [];

                                foreach ($methods as $_method):
                                        $code = $_method->getCode();
                                        $checked = $block->getSelectedMethodCode() === $code;

                                    if (isset($methodsForms[$code])) {
                                        $block->setMethodFormTemplate($code, $methodsForms[$code]);
                                    }
                                    ?>
                                    <div data-bind="scope: 'payment_method_<?= $block->escapeHtml($code);?>'">
                                        <dt class="item-title">
                                            <?php if ($methodsCount > 1): ?>
                                                <input type="radio"
                                                    id="p_method_<?= $block->escapeHtml($code); ?>"
                                                    value="<?= $block->escapeHtml($code); ?>"
                                                    name="payment[method]"
                                                    title="<?= $block->escapeHtml($_method->getTitle()) ?>"
                                                    <?php if ($checked): ?>
                                                        checked="checked"
                                                    <?php endif; ?>
                                                    class="radio"/>
                                            <?php else: ?>
                                                <input type="radio"
                                                    id="p_method_<?= $block->escapeHtml($code); ?>"
                                                    value="<?= $block->escapeHtml($code); ?>"
                                                    name="payment[method]"
                                                    checked="checked"
                                                    class="radio solo method" />
                                            <?php endif; ?>
                                            <label for="p_method_<?= $block->escapeHtml($code); ?>">
                                                <?= $block->escapeHtml($_method->getTitle()) ?>
                                            </label>
                                        </dt>
                                        <?php if ($html = $block->getChildHtml('payment.method.' . $code)): ?>
                                            <dd class="item-content <?= $checked ? '' : 'no-display'; ?>">
                                                <?= /* @noEscape */ $html; ?>
                                            </dd>
                                        <?php endif; ?>
                                    </div>
                                <?php endforeach; ?>
                            </dl>
                            <?= $block->getChildHtml('payment_methods_after') ?>
                            <?= $block->getChildHtml('checkout_billing_items') ?>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>




    </form>
    </div>

<div id ="wk_osc_overview_div">
<!-- <div class="wk_add_content">
        <div class="wk-loading-mask wk-display-none">
    <div class="wk-loader"></div>
</div> -->
<!-- <div class="wk_osc_title"> Overview </div> -->
<form
      style="float:right;width:100%;"
      action="<?= $block->escapeUrl($block->getUrl('multishipping/checkout/overviewPost')); ?>"
      method="post"
      id="review-order-form"
      data-mage-init='{"orderOverview": {}, "validation":{}}'
      class="form multicheckout order-review">

</form>
</div>
<div id = "adddress-popup-modal" style="display:none">
        <?php
        //echo $this->getBlockHtml('checkout_address_select');//'formkey')
        //echo $this->getChildHtml('customer_address_edit')
        ?>
</div>

<?php
$exportValues = [
    'choose_billing' => '#wk_choose_billing',
    'modal_html' => '#adddress-popup-modal',
];
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$jsonHelper = $objectManager->create(\Magento\Framework\Json\Helper\Data::class);

$serializedExportValues = $jsonHelper->jsonEncode($exportValues);
?>

<script type="text/x-magento-init">
    {
        "*": {
            "billing": <?= /*@noEscape*/ $serializedExportValues; ?>
        }
    }
</script>

<script>
    require(['jquery', 'mage/mage'], function(jQuery) {
        var addtocartForm = jQuery('#multishipping-billing-form');

        addtocartForm.mage('payment', {
            checkoutPrice: <?= (float)$block->getQuoteBaseGrandTotal() ?>
        });

        addtocartForm.mage('validation', {
            errorPlacement: function(error, element) {
                if (element.attr('data-validate') && element.attr('data-validate').indexOf('validate-cc-ukss') >= 0) {
                    element.parents('form').find('[data-validation-msg="validate-cc-ukss"]').html(error);
                } else {
                    element.after(error);
                }
            }
        });
    });
</script>

<script>
    //<![CDATA[
    require(
        [
            'Magento_Checkout/js/model/quote',
            'jquery',
            'domReady!'
        ], function(quote, $) {
            quote.billingAddress({
                    city: "<?= $block->escapeJs($block->getAddress()->getCity()) ?>",
                    company: "<?= $block->escapeJs($block->getAddress()->getCompany()); ?>",
                    countryId: "<?= $block->escapeJs($block->getAddress()->getCountryId()); ?>",
                    customerAddressId: '<?= /* @noEscape */ $block->getAddress()->getCustomerAddressId(); ?>',
                    customerId: '<?= /* @noEscape */ $block->getAddress()->getCustomerId(); ?>',
                    fax: "<?= $block->escapeJs($block->getAddress()->getFax()); ?>",
                    firstname: "<?= $block->escapeJs($block->getAddress()->getFirstname()); ?>",
                    lastname: "<?= $block->escapeJs($block->getAddress()->getLastname()); ?>",
                    postcode: "<?= $block->escapeJs($block->getAddress()->getPostcode()); ?>",
                    regionId: "<?=  $block->escapeJs($block->getAddress()->getRegionId()); ?>",
                    regionCode: "<?= $block->escapeJs($block->getAddress()->getRegionCode()); ?>",
                    region: "<?= $block->escapeJs($block->getAddress()->getRegion()); ?>",
                    street: <?= /* @noEscape */ json_encode($block->escapeJs($block->getAddress()->getStreet())); ?>,
                    telephone: "<?=  $block->escapeJs($block->getAddress()->getTelephone()); ?>"
            });
        });
    //]]>
</script>
